### ISSUE TITLE
Update `request` semver in `package.json`

### ISSUE THREAD

**Issue by ghchinoy** [soaErikNord/deployCM#3]
Currently `request` is `~1.9.x`, but I think it should be something more recent (say `~2.0.0` or `>2.0.0`).

Receiving an error after cloning, `npm install`, and `npm start` which is corrected by changing the `package.json` `request` semver to `~2.0.0` or `>2.0.0`

Not sure why something that worked in the past is now erroring out, may be an updated node version?

Would've submitted a PR, but I've pending PR's on my fork and didn't want to conflate the two.

```
> node ./bin/www

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/hchinoy/dev/Akana/projects/deployCM/bin/www'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.12.0
npm ERR! code ELIFECYCLE
npm ERR! deployCM@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deployCM@0.0.1 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the deployCM package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls deployCM
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hchinoy/dev/Akana/projects/deployCM/npm-debug.log
```

npm-debug.log

``````
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.12.0
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart deployCM@0.0.1
7 info start deployCM@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info deployCM@0.0.1 Failed to exec start script
10 verbose stack Error: deployCM@0.0.1 start: `node ./bin/www`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid deployCM@0.0.1
12 verbose cwd /Users/hchinoy/dev/Akana/projects/deployCM
13 error Darwin 14.4.0
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.2
16 error npm  v2.12.0
17 error code ELIFECYCLE
18 error deployCM@0.0.1 start: `node ./bin/www`
18 error Exit status 1
19 error Failed at the deployCM@0.0.1 start script 'node ./bin/www'.
19 error This is most likely a problem with the deployCM package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node ./bin/www
19 error You can get their info via:
19 error     npm owner ls deployCM
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]```
``````

**Comment by soaErikNord** [comment]
Updated.
